name: Terraform GCP Deployment

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  terraform:
    name: Terraform Pipeline
    runs-on: ubuntu-latest

    env:
      GOOGLE_APPLICATION_CREDENTIALS: ${{ github.workspace }}/gcp-key.json

    steps:
      # 🧩 Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # 🧩 Step 2: Set up Terraform
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.5

      # 🧩 Step 3: Authenticate to Google Cloud
      # Make sure your GCP key is Base64 encoded when added as a secret
      - name: Authenticate to Google Cloud
        run: |
          echo "${
